# Generated by Django 3.2 on 2023-04-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230411_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '1级'), (2, '2级'), (4, '4级'), (3, '3级')], default=1, verbose_name='级别'),
        ),
    ]
